### ISSUE TITLE
bson-0.4.11 not found

### ISSUE THREAD

**Issue by Tharbad** [linnovate/icapi#68]
On docker build, I get:
http fetch GET https://registry.npmjs.org/bson/-/bson-0.4.11.tgz
npm http fetch 504 https://registry.npmjs.org/bson/-/bson-0.4.11.tgz
npm ERR! fetch failed https://registry.npmjs.org/bson/-/bson-0.4.11.tgz

https://registry.npmjs.org/bson/-/bson-0.4.11.tgz gives {"error":"package could not be found."}

Ideas?

**Comment by assafSabag** [comment]
i get it on npm install
do you fix it?

**Comment by assafSabag** [comment]
I update bson version in npm-shrinkwrap.json
